openapi: 3.0.3
info:
  title: Running High API Server
  description: '러닝하이 API'
  version: '1.1.0'
servers:
  - url: http://localhost:3000
    description: 로컬 환경
  - url: https://www.sosocamp.shop
    description: AWS EC2 서버
tags:
  - name: User
    description: 사용자 계정
  - name: Auth
    description: 로그인/회원가입
  - name: Reward
    description: 리워드
paths:
  /auth/signUp/emailVerification:
    post:
      tags:
        - Auth
      summary: 로컬계정 회원가입 이메일 인증
      requestBody:
        description: 인증 이메일 정보
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  description: 인증 이메일
                  type: string
            example:
              email: 'bbaekddo100@naver.com'
      responses:
        '200':
          description: OK
  /auth/signUp/emailVerification/code:
    post:
      tags:
        - Auth
      summary: 로컬계정 회원가입 이메일 인증 완료
      requestBody:
        description: 이메일 인증 코드
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  description: 인증코드 받은 이메일 주소
                  type: string
                code:
                  description: 이메일 인증 코드
                  type: integer
            example:
              email: 'bbaekddo100@naver.com'
              code: 123456
      responses:
        '200':
          description: OK
  /auth/signUp/nickname:
    post:
      tags:
        - Auth
      summary: 닉네임 중복 검사
      requestBody:
        description: 닉네임 중복 검사
        content:
          application/json:
            schema:
              type: object
              properties:
                nickname:
                  description: 중복 검사용 닉네임
                  type: string
            example:
              nickname: 런닝맨
      responses:
        '200':
          description: OK
  /auth/signUp:
    post:
      tags:
        - Auth
      summary: 로컬계정 회원가입
      requestBody:
        description: 회원가입 정보
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  description: 회원가입 이메일 주소
                  type: string
                nickname:
                  description: 회원가입 닉네임
                  type: string
                password:
                  description: 회원가입 비밀번호
                  type: string
            example:
              email: 'bbaekddo100@naver.com'
              nickname: 런닝맨
              password: TestPass1!
      responses:
        '200':
          description: OK
  /auth/oauth/authroization:
    get:
      tags:
        - Auth
      summary: OAuth 인가코드 링크
      description: Redirection URL => https://running-high.ml/login
      parameters:
        - name: provider
          in: query
          description: 플랫폼 공급자
          required: true
      responses:
        '200':
          description: OK
  /auth/signIn/local:
    post:
      tags:
        - Auth
      summary: 로컬계정 로그인
      requestBody:
        description: 로그인 정보
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  description: 로그인 이메일
                  type: string
                password:
                  description: 로그인 비밀번호
                  type: string
            example:
              email: 'bbaekddo100@naver.com'
              password: TestPass1!
      responses:
        '200':
          description: OK
  /auth/signIn/kakao:
    get:
      tags:
        - Auth
      summary: 카카오 로그인
      parameters:
        - name: code
          in: query
          description: 카카오 인가코드
          required: true
      responses:
        '200':
          description: OK
  /auth/oauth/addInfo:
    post:
      tags:
        - Auth
      summary: 카카오 회원가입 추가정보 등록
      parameters:
        - name: x-access-token
          in: header
          description: 사용자 액세스 토큰
          required: true
      requestBody:
        description: 회원가입 정보
        content:
          application/json:
            schema:
              type: object
              properties:
                nickname:
                  description: 회원가입 닉네임
                  type: string
      responses:
        '200':
          description: OK
  /auth/refresh:
    get:
      tags:
        - Auth
      summary: 사용자 액세스 토큰 재발급
      parameters:
        - name: refreshToken
          in: cookie
          description: 재발급 토큰
          required: true
      responses:
        '200':
          description: OK
  /auth/logout:
    get:
      tags:
        - Auth
      summary: 로그아웃
      parameters:
        - name: x-access-token
          in: header
          description: 사용자 액세스 토큰
          required: true
      responses:
        '200':
          description: OK
  /auth/userInfo/emailVerification:
    post:
      tags:
        - Auth
      summary: 비밀번호 찾기 이메일 인증 시작
      requestBody:
        description: 비밀번호 찾기 정보
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  description: 인증코드 받을 이메일 주소
                  type: string
            example:
              email: 'bbaekddo100@naver.com'
      responses:
        '200':
          description: OK
  /auth/userInfo/emailVerification/code:
    post:
      tags:
        - Auth
      summary: 비밀번호 찾기 이메일 인증 완료
      requestBody:
        description: 비밀번호 찾기 정보
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  description: 인증코드 받은 이메일 주소
                  type: string
                code:
                  description: 이메일 인증코드
                  type: string
            example:
              email: 'bbaekddo100@naver.com'
              code: ak8Bs729D2ls
      responses:
        '200':
          description: OK
  /users/myPage/userInfo:
    post:
      tags:
        - User
      summary: 비밀번호 변경
      parameters:
        - name: x-access-token
          in: header
          description: 사용자 액세스 토큰
          required: true
      requestBody:
        description: 사용자 정보
        content:
          application/json:
              schema:
                type: object
                properties:
                  userId:
                    description: 사용자 ID
                    type: integer
                  currentPassword:
                    description: 현재 비밀번호
                    type: string
                  newPassword:
                    description: 변경 비밀번호
                    type: string
              example:
                userId: 1
                currentPassword: pass1
                newPassword: pass2
      responses:
        '200':
          description: OK
  /users/myPage/withdrawal:
    post:
      tags:
        - User
      summary: 회원탈퇴
      parameters:
        - name: x-access-token
          in: header
          description: 사용자 액세스 토큰
          required: true
      requestBody:
        description: 탈퇴 회원 정보
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  description: 사용자 ID
                  type: integer
                password:
                  description: 사용자 비밀번호
                  type: string
            example:
              userId: 1
              password: TestPass1!
      responses:
        '200':
          description: OK
  /rewards/users:
    get:
      tags:
        - Reward
      summary: 리워드 메인 페이지
      parameters:
        - name: x-access-token
          in: header
          description: 사용자 액세스 토큰
          required: true
      responses:
        '200':
          description: OK
  /rewards/running/exercise:
    get:
      tags:
        - Reward
      summary: 운동 선택
      parameters:
        - name: x-access-token
          in: header
          description: 사용자 액세스 토큰
          required: true
        - name: type
          in: query
          description: '운동 종류 (그룹운동 : G / 개인운동 : P)'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
  /rewards/running/start:
    post:
      tags:
        - Reward
      summary: 운동 시작
      parameters:
        - name: x-access-token
          in: header
          description: 사용자 액세스 토큰
          required: true
      requestBody:
        required: true
        description: 사용자 위치 정보
        content:
          application/json:
            schema:
              type: object
              properties:
                longitude:
                  description: 현재 위치의 경도
                  type: string
                latitude:
                  description: 현재 위치의 위도
                  type: string
            example:
              longitude: '127.04121226963451'
              latitude: '37.54551935928244'
      responses:
        '200':
          description: OK
  /rewards/running/check:
    post:
      tags:
        - Reward
      summary: 운동 진행
      parameters:
        - name: x-access-token
          in: header
          description: 사용자 액세스 토큰
          required: true
        - name: isRestart
          in: query
          description: 운동 일시정지 후 재시작 여부
          required: true
          schema:
            type: boolean
      requestBody:
        required: true
        description: 사용자 위치 정보
        content:
          application/json:
            schema:
              type: object
              properties:
                longitude:
                  description: 현재 위치의 경도
                  type: string
                latitude:
                  description: 현재 위치의 위도
                  type: string
            example:
              longitude: '127.04028456049792'
              latitude: '37.545871069059146'
      responses:
        '200':
          description: OK
  /rewards/running/stop:
    post:
      tags:
        - Reward
      summary: 운동 일시정지
      parameters:
        - name: x-access-token
          in: header
          description: 사용자 액세스 토큰
          required: true
      requestBody:
        required: true
        description: 사용자 위치 정보
        content:
          application/json:
            schema:
              type: object
              properties:
                longitude:
                  description: 현재 위치의 경도
                  type: string
                latitude:
                  description: 현재 위치의 위도
                  type: string
            example:
              longitude: '127.03916444811568'
              latitude: '37.54617778554935'
      responses:
        '200':
          description: OK
  /rewards/running/end:
    post:
      tags:
        - Reward
      summary: 운동 종료
      parameters:
        - name: x-access-token
          in: header
          description: 사용자 액세스 토큰
          required: true
        - name: forceEnd
          in: query
          description: 운동 강제 종료 여부
          required: true
          schema:
            type: boolean
      requestBody:
        required: true
        description: 사용자 위치 정보
        content:
          application/json:
            schema:
              type: object
              properties:
                longitude:
                  description: 현재 위치의 경도
                  type: string
                latitude:
                  description: 현재 위치의 위도
                  type: string
            example:
              longitude: '127.03821384085329'
              latitude: '37.54604294715771'
      responses:
        '200':
          description: OK
  /rewards/running/proofImage:
    post:
      tags:
        - Reward
      summary: 운동 인증사진 업로드
      parameters:
        - name: x-access-token
          in: header
          description: 사용자 액세스 토큰
          required: true
      requestBody:
        required: true
        description: 운동 인증사진
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                exercise_id:
                  description: 운동 기록 ID
                  type: integer
                image:
                  description: 운동 사진
                  type: string
                  format: base64
            example:
              exercise_id: 1
              image: 'exercise.jpg'
      responses:
        '200':
          description: OK